a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from a_users.views import profile_view
from a_home.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),

    path('', include('a_rchat.urls')),
    path('profile/', include('a_users.urls')),
    path('@<username>/', profile_view, name="profile"),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import  path
from django.shortcuts import render, redirect

from . import views

app_name = "account"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.sign_in, name="login"),
    path("logout/", views.logout, name="logout"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("", views.dashboard, name="dashboard"),
    path('forgot_password/', views.forgot_password, name="forgot_password"),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name="reset_password_validate"),
    path('reset_password/', views.reset_password, name="reset_password"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField



class AccountManeger(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("email is required")

        if not username:
            raise ValueError("username is required")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save()
        return user

    def create_superuser(
        self, first_name, last_name, email, username, phone_number, password
    ):
        if not email:
            raise ValueError("email is required")
        if not username:
            raise ValueError("username is required")

        if self.model.objects.filter(username=username).exists():
            raise ValueError("Superuser creation failed: Username already exists.")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )

        user.is_admin = True
        user.is_staff = True
        user.is_active = True
        user.is_superadmin = True

        user.set_password(password)
        user.save()
        return user

class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    phone_number = PhoneNumberField(null=True, blank=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name", "phone_number"]

    objects = AccountManeger()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

users/forms.py
from django import forms
from .models import Account

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email',"phone_number", 'password']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs = {'placeholder': 'First Name',type:'text'}
        self.fields['last_name'].widget.attrs = {'placeholder': 'Last Name',type:'text'}
        self.fields['email'].widget.attrs = {'placeholder': 'Email',type:'email'}
        self.fields['phone_number'].widget.attrs = {'placeholder': 'Phone Number',type:'tel'}
        self.fields['password'].widget.attrs = {'placeholder': 'Password',type:'password'}
        self.fields['confirm_password'].widget.attrs = {'placeholder': 'confirm password',type:'password'}
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("Passwords must match")

users/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
import requests
from .forms import RegisterForm
from .models import Account

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            phone_number = form.cleaned_data['phone_number']
            username = email.split('@')[0]
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, password=password, username=username)
            user.phone_number = phone_number
            user.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            message = render_to_string('verification.html',{
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token(user)
            })

            send_mail(
                'Email Verification',
                f'Please verify your mail',
                settings.DEFAULT_FROM_EMAIL,
                (email,),
                html_message=message,
                fail_silently=False,
            )

            messages.success(request,"Regiteration is successfully done.")
            messages.success(request, f'Account created for {first_name} {last_name}! please verify your email to verify.')
            return redirect("account:login")

    else:
        form = RegisterForm()

    context = {'form': form}
    return render(request, 'register.html', context)



def sign_in(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)
        auth.login(request, user)
        messages.success(request, f'You are now logged in!')
        return redirect('home')

    return render(request,"signin.html")


@login_required(login_url='account:login')
def logout(request):
    auth.logout(request)
    messages.success(request, f'You are now logged out!')
    return redirect('account:login')



def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        print("entered exception ")
        user = None
    if user is not None and default_token_generator.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, f'Account has been activated.')
        return redirect('account:login')
    else:
        print("user does not exist")
        messages.error(request, 'Activation link is invalid!')
        return redirect('account:register')


@login_required(login_url="account:login")
def dashboard(request):

    return render(request, 'dashboard.html')



def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            current_site = get_current_site(request)
            message = render_to_string('reset_password_validate.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user)
            })

            send_mail(
                'Password Reset email',
                f'Please verify your mail',
                settings.DEFAULT_FROM_EMAIL,
                (email,),
                html_message=message,
                fail_silently=False,
            )
            messages.success(request,'password reset email has been sent successfully.')

            return redirect('account:login')

        else:
            messages.error(request, 'Account does not exist!')


    return render(request,'forgotpassword.html')


def reset_password_validate(request,uidb64,token):
    print ("entered function")
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        print("entered exception ")
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'please reset your password.')
        return redirect('account:reset_password')
    else:
        messages.error(request, 'this link has been expired.')
        return redirect('account:forgotpassword')



def reset_password(request):
    if request.method == 'POST':
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')

        if new_password == confirm_password:
            try:
                uid = request.session.get('uid')
                user = Account.objects.get(pk=uid)
                user.set_password(new_password)
                user.save()
                messages.success(request, "Password reset successfully.")
                return redirect('account:login')
            except Account.DoesNotExist:
                messages.error(request, "User not found.")
        else:
            messages.error(request, "Passwords do not match.")
    return render(request, 'reset_password.html')

users/templates/forgotpassword.html
{% extends 'layouts/blank.html' %}
{% block content %}


    
    
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Forgot password</h4>
          {% include "includes/alerts.html" %}
      <form action="{% url 'account:forgot_password'%}" method="POST">
          
          {% csrf_token %}
          <div class="form-group">
			 <input aria-label="email" type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->

          
          <div class="form-group">
          	<a href="{%  url 'account:login' %}" class="float-right">Got Password? Login </a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'account:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

users/templates/register.html
{% extends 'layouts/blank.html' %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
{#          {% include "includes/alerts.html" %}#}
          
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form action="{% url 'account:register' %}" method="POST">
            {% csrf_token %}
				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
                        {{ form.first_name }}
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Last name</label>
                        {{ form.last_name }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->
				<div class="form-group">
					<label>Email</label>
                        {{ form.email }}
				</div> <!-- form-group end.// -->
				
				<div class="form-row">
					<div class="form-group col-md-6">
					  <label>Phone number</label>
                        {{ form.phone_number }}
					</div> <!-- form-group end.// -->
			
				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
                        {{ form.password }}
					</div> <!-- form-group end.// --> 
					<div class="form-group col-md-6">
						<label>Repeat password</label>
                    {{ form.confirm_password }}
					</div> <!-- form-group end.// -->  
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			    </div> <!-- form-group// -->      
			        {{ form.email.errors }}
                    {{ form.non_field_errors }}
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'account:login' %}">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

users/templates/reset_password.html
{% extends 'layouts/blank.html' %}
{% block content %}


    
    
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Reset your password</h4>
          {% include "includes/alerts.html" %}
      <form action="{% url 'account:reset_password'%}" method="POST">
          
          {% csrf_token %}
          <div class="form-group">
			 <input aria-label="email" type="password" class="form-control" placeholder="New password" name="new_password">
          </div> <!-- form-group// -->

          <div class="form-group">
			 <input aria-label="email" type="password" class="form-control" placeholder="Confirm your password" name="confirm_password">
          </div>
          <div class="form-group">
          	<a href="{%  url 'account:login' %}" class="float-right">Got Password? Login </a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Reset  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'account:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

users/templates/reset_password_validate.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Email Verification</title>
    <style>

        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        .email-container {
            max-width: 600px;
            margin: 20px auto;
            background: #ffffff;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .email-header {
            text-align: center;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .email-button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .email-footer {
            text-align: center;
            font-size: 0.9em;
            color: #555;
            margin-top: 20px;
        }
    
    </style>
</head>
<body>
    <div class="email-container">
        <div class="email-header">
            <h1>Email Verification</h1>
        </div>
         {% autoescape off %}
        <p>Hi {{ user.username }},</p>
        <p>Thank you for signing up. Please verify your email address by clicking the link below:</p>
        <p>
            <a href="http://{{ domain }}{% url 'account:reset_password_validate' uidb64=uid token=token %}" class="email-button">Verify Email</a>
        </p>
        <p>If the button above does not work, you can also copy and paste the following link into your browser:</p>
        <p>
            http://{{ domain }}{% url 'account:reset_password_validate' uidb64=uid token=token %}

        </p>
        <p>If you did not create an account, you can safely ignore this email.</p>
        {% endautoescape %}

        <div class="email-footer">
            <p>&copy; {{ domain }} {{ "now"|date:"Y" }}</p>
            
        </div>
    </div>
</body>
</html>

users/templates/signin.html
{% extends 'layouts/blank.html' %}
{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
    
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
{#          {% include "includes/alerts.html" %}#}
      <form action="{% url 'account:login'%}" method="POST">
          
          {% csrf_token %}
          <div class="form-group">
			 <input aria-label="email" type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->
          <div class="form-group">
			<input aria-label="password" type="password" class="form-control" placeholder="Password" name="password">
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="{% url 'account:forgot_password' %}" class="float-right">Forgot password?</a>
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="{% url 'account:register' %}">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

users/templates/verification.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Email Verification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        .email-container {
            max-width: 600px;
            margin: 20px auto;
            background: #ffffff;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .email-header {
            text-align: center;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .email-button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }
        .email-footer {
            text-align: center;
            font-size: 0.9em;
            color: #555;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="email-header">
            <h1>Email Verification</h1>
        </div>
        {% autoescape off %}
        <p>Hi {{ user.username }},</p>
        <p>Thank you for signing up. Please verify your email address by clicking the link below:</p>
        <p>
        http://{{ domain }}/{% url 'account:activate' uidb64=uid token=token %}" class="email-button
            <a href="http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}" class="email-button">Verify Email</a>
        </p>
        <p>If the button above does not work, you can also copy and paste the following link into your browser:</p>
        <p><a href="http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}">http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}</a></p>
        <p>If you did not create an account, you can safely ignore this email.</p>
        <div class="email-footer">
            <p>&copy; {{ domain }} {{ "now"|date:"Y" }}</p>
                    {% endautoescape %}z

        </div>
    </div>
</body>
</html>

{##}
{#{% autoescape off %}#}
{#    #}
{#http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}#}
{#{% endautoescape %}#}
{##}